ClusterName=lab
SlurmctldHost=slurmctld

AuthType=auth/munge
CredType=cred/munge

SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818

SlurmctldPidFile=/run/slurm/slurmctld.pid
SlurmdPidFile=/run/slurm/slurmd.pid
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

ProctrackType=proctrack/linuxproc
TaskPlugin=task/affinity
SwitchType=switch/none
MpiDefault=none

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

ReturnToService=2
SlurmdParameters=config_overrides
MaxNodeCount=64
TreeWidth=64

GresTypes=gpu

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
AccountingStoragePort=6819
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

SlurmctldDebug=info
SlurmdDebug=info

PartitionName=main Nodes=ALL Default=YES MaxTime=INFINITE State=UP
